# Copyright (c) 2025 Analog Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: no-os
      url-base: https://github.com/analogdevicesinc/no-OS.git

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - cmsis
    - name: no-os
      remote: no-os
      revision: HEAD~0
      path: no-os/

  self:
    path: adi-zephyr-sdk